### ISSUE TITLE
Populate Repository

### ISSUE THREAD

**Issue by ericrtung** [coderfin/AccentOccurrences#1]
Hi! I presume this was intended to be the repository for the following plugin: https://visualstudiogallery.msdn.microsoft.com/2f4627df-98ca-4ce1-9187-8eec7a67ba8c

I love this plugin and would really like to see the code get added to GitHub.

Thanks!
- Eric

**Comment by coderfin** [comment]
@ericrtung hope this helps.  I updated the extension to support VS 2015.  If you would like to contribute by adding a new feature or bug fix a pull request would be great!

**Comment by ericrtung** [comment]
I would love to! This is honestly the only occurrence highlighter that works well on the dark theme and has great editor customize-ability. And with the update I don't have to hack the .visx file any more to get it to work in 2015 ;)
