### ISSUE TITLE
Selection hang a few seconds

### ISSUE THREAD

**Issue by sdalexandre** [coderfin/AccentOccurrences#6]
With Visual Studio 2015 community, with a C# project (Generated with Unity3D).

When the cursor is inside a word and the default Visual Studio highlight appear, starting a selection from an empty space of the code make the Visual Studio hang for a few seconds.

**Comment by coderfin** [comment]
I no longer use Visual Studio (switched to VS Code) and no longer have the time to maintain or update this repository. I intentionally made if public and to allow others to contribute and fork the repo.  If you would like to contribute a fix I would gladly consider a pull request.

**Comment by jarstelfox** [comment]
@sdalexandre out of curiosity, is this the same as #5 (I reported this, but couldn't find steps to reproduce)

**Comment by coderfin** [comment]
Closing issue in preparation to archive this repository.
